/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Estefanía Aguilar
 */
public class FmCambioConstrasenia extends javax.swing.JFrame {

    /**
     * Creates new form FmCambioConstrasenia
     */
    public FmCambioConstrasenia() {
        initComponents();
        this.setTitle("Editar perfil");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContraActual = new javax.swing.JLabel();
        lblContraNueva = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        txtContraNueva = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblContraseña = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblAzul = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContraActual.setForeground(new java.awt.Color(0, 0, 0));
        lblContraActual.setText("Contraseña actual:");
        getContentPane().add(lblContraActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblContraNueva.setForeground(new java.awt.Color(0, 0, 0));
        lblContraNueva.setText("Contraseña nueva:");
        getContentPane().add(lblContraNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 30));

        txtContraNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, 30));

        btnAceptar.setBackground(new java.awt.Color(204, 204, 204));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/si.png"))); // NOI18N
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prohibido.png"))); // NOI18N
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContraseña.setText("Contraseña");
        lblContraseña.setToolTipText("");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, 30));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contrasena.png"))); // NOI18N
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lblEditar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(0, 0, 0));
        lblEditar.setText("Editar");
        getContentPane().add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 50, -1));

        lblAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/azul638.jpg"))); // NOI18N
        getContentPane().add(lblAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 80));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blancosolido.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmCambioConstrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmCambioConstrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmCambioConstrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmCambioConstrasenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmCambioConstrasenia().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/pluma.png"));
        return retValue;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblAzul;
    private javax.swing.JLabel lblContraActual;
    private javax.swing.JLabel lblContraNueva;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JTextField txtContraNueva;
    private javax.swing.JTextField txtContrasenia;
    // End of variables declaration//GEN-END:variables
}
