/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import entidades.Chat;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Estefanía Aguilar
 */
public class FmChat extends javax.swing.JFrame {

    /**
     * Creates new form FmChat
     */
    public FmChat(Frame padre, Chat chat) {
        initComponents();
        this.setTitle("Juatsapp");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloChat = new javax.swing.JTextField();
        lblIcon = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnMensaje = new javax.swing.JTextField();
        lblGris = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTituloChat.setEditable(false);
        txtTituloChat.setBorder(null);
        getContentPane().add(txtTituloChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 290, 30));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bocadillo32.png"))); // NOI18N
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviar.png"))); // NOI18N
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        btnMensaje.setBackground(new java.awt.Color(255, 255, 255));
        btnMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(btnMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 50));

        lblGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gris500.jpg"))); // NOI18N
        getContentPane().add(lblGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 390, 360));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blancosolido.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

            
    
      @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/whatsapp.png"));
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JTextField btnMensaje;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGris;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JTextField txtTituloChat;
    // End of variables declaration//GEN-END:variables
}
