package Forms;

import Enum.Sexo;
import entidades.Usuario;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import repositories.UsuarioRepository;

/**
 *
 * @author Estefanía Aguilar
 */
public class FmRegistrar extends javax.swing.JFrame {

    UsuarioRepository usuarioRepository;

    /**
     * Creates new form FmRegistrar
     */
    public FmRegistrar(Frame padre) {
        initComponents();
        this.setTitle("Juatsapp");
        this.setLocationRelativeTo(null);
        usuarioRepository = new UsuarioRepository();
        //Cargar en el bombo box los sexos disponibles.
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement(Sexo.FEMENINO);
        modelo.addElement(Sexo.MASCULINO);
        modelo.addElement(Sexo.ROBOT);
        cbSexo.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        lblJuatsapp = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/whatsappM.png"))); // NOI18N
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        lblRegistro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblRegistro.setText("Registro");
        getContentPane().add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblJuatsapp.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        lblJuatsapp.setForeground(new java.awt.Color(51, 102, 255));
        lblJuatsapp.setText("Juatsapp");
        getContentPane().add(lblJuatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, 50));

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        lblEdad.setText("Edad:");
        getContentPane().add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblSexo.setText("Sexo:");
        getContentPane().add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        lblCorreo.setText("Correo:");
        getContentPane().add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        lblContrasenia.setText("Contraseña:");
        getContentPane().add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 80, 30));

        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, 30));

        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 200, 30));

        getContentPane().add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, 30));

        btnRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrar.setText("Registrarse");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 120, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blancosolido.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (validarCampos() && validarCorreo()) {
            guardarBD();
            mostrarMensaje();
            FmInicioSesion fmIniciarSesion = new FmInicioSesion();
            fmIniciarSesion.show();
            setVisible(false);
//        }else{
//           mostrarMensajeError();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        if (!String.valueOf(evt.getKeyChar()).matches("^[0-9]$")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (!String.valueOf(evt.getKeyChar()).matches("^[a-zA-Z ñáéíóú]$")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped
    /**
     * Metodo que se encarga de validar que todos los campos esten llenos al
     * momento de almacenar.
     *
     * @return Indica si todos los campos estan llenos o no.
     */
    private boolean validarCampos() {
        if (!txtNombre.getText().isEmpty()
                && !txtEdad.getText().isEmpty()
                && !txtCorreo.getText().isEmpty()
                && !txtContrasenia.getText().isEmpty()) {
            return true;
        }
        mostrarMensajeError();
        return false;
    }

    public boolean validarCorreo() {
        // Patrón para validar el correo
        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        Matcher mather = pattern.matcher(txtCorreo.getText());
        if (mather.find() == true) {            
            return true;
        } else {            
            JOptionPane.showMessageDialog(this, "El correo ingresado es inválido.",
                    "Alerta", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    /**
     * Metodo que se encarga de guardar un usuario en la base de datos.
     */
    private void guardarBD() {
        Usuario usuario = new Usuario(txtNombre.getText(), txtContrasenia.getText(),
                 txtCorreo.getText(), Integer.parseInt(txtEdad.getText()), (Sexo) cbSexo.getSelectedItem());

        usuarioRepository.guardar(usuario);
    }

    /**
     * Método que se encarga de mostrar un mensaje indicando que faltan campos
     * por llenar.
     */
    private void mostrarMensajeError() {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Alerta", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * Método que se encarga de mostrar un mensaje indicando que se ha
     * registrado el usuario con exito.
     */
    private void mostrarMensaje() {
        JOptionPane.showMessageDialog(this, "Registro exitoso.", "Exito", JOptionPane.WARNING_MESSAGE);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/whatsapp.png"));
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblJuatsapp;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
